config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :orders

  resources :products

  resources :charges

  resources :order_products

  get 'checkout' => 'order_products#checkout'
  

  root 'products#index'

end

app/models/order_product.rb
# == Schema Information
#
# Table name: order_products
#
#  id         :integer          not null, primary key
#  order_id   :integer
#  product_id :integer
#  quantity   :integer
#  created_at :datetime
#  updated_at :datetime
#

class OrderProduct < ActiveRecord::Base
  attr_accessible :order_id, :product_id, :quantity

  # validates :order_id, :presence => true
  validates :product_id, :presence => true
  validates :quantity, :presence => true

  belongs_to :order
  belongs_to :product

  def self.total(price)
    subtotal_array = price.map { |price| price.product.price * price.quantity }.inject(:+)
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :set_order_product, only: [:show, :edit, :update, :destroy]

  # GET /order_products
  # GET /order_products.json
  def index
    if session[:cart]
      @order_products = OrderProduct.find session[:cart]
      @total = OrderProduct.total(@order_products)
    else
      @order_products = []
    end
  end

  # GET /order_products/1
  # GET /order_products/1.json
  def show
    @order_products = OrderProduct.where()
  end

  # GET /order_products/new
  def new
    @order_product = OrderProduct.new
  end

  # GET /order_products/1/edit
  def edit
  end

  # POST /order_products
  # POST /order_products.json
  def create
    @order_product = OrderProduct.create(params[:order_product])

    respond_to do |format|
      if @order_product.save
        session[:cart] ||= []
        session[:cart].push @order_product.id

        output = {'status' => 'Item was successfully added to cart.'}.to_json

        format.html { redirect_to order_products_path, notice: 'Item was successfully added to cart.' }
        format.json { render :json => output }
      else
        format.html { render :new }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # User proceed to payment from here.
  def checkout
    session[:order_id] = nil #add this to clear order_id hash everytime. fix heroku issue
    # Everytime proceed to checkout, first thing to do is to check whether the order id in the session cart{:order_id}, otherwise create a new one
    @order = Order.find session[:order_id] || Order.create(:user_id => current_user.id)
    session[:order_id] = @order.id
    
    @updatedPrice = calc_total_price || ''

    # Associate each item in the cart with the new order id.
    session[:cart].each do |order_product_id|
      item = OrderProduct.find order_product_id
      item.order_id = @order.id
      item.save
    end
  end

  # PATCH/PUT /order_products/1
  # PATCH/PUT /order_products/1.json
  def update
    respond_to do |format|
      if @order_product.update(order_product_params)
        format.html { redirect_to @order_product, notice: 'Order product was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_product }
      else
        format.html { render :edit }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_products/1
  # DELETE /order_products/1.json
  def destroy
    # clear the product id in Cart before destroying the orderproduct. Otherwise cause problem when redirect to the index page after that, because no longer can find the same product id again.
    session[:cart].delete(params[:id].to_i)

    @updatedPrice = calc_total_price || ''
    # Destroy the item and redirect back to the same page.
    @order_product.destroy

    output = {'status' => 'Item was successfully removed from cart.', 'updatedPrice' => @updatedPrice}.to_json

    respond_to do |format|
      format.html { redirect_to order_products_url, notice: 'You have successfully removed one item from your shopping cart.' }
      format.json { render :json => output }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product
      @order_product = OrderProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_product_params
      params[:order_product]
    end
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/views/order_products/_form.html.erb
<%= form_for(@order_product) do |f| %>
  <% if @order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
      <% @order_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_products/checkout.html.erb
<div class="timer">
    Loading...
</div>
<span class="lead"><b>  Checkout Page</b></span>
<h4>Proceeding to payment ...</h4><hr>

<ul>
  <% @order.products.each do |order| %>
    <li class="list_item lead"><i class="glyphicon glyphicon-ok text-success"></i> <%= order.title %></li>
  <% end %>
</ul>
<hr>


<!-- for stripe -->
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span class="lead">Total Amount:<b> $<%= @updatedPrice %>0 AUD</b></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Pleas fill up the form."
          data-billing-address= 'true'
          data-shipping-address= 'true'
          data-amount="<%= (@updatedPrice * 100).to_i %>"></script>
<% end %>

app/views/order_products/edit.html.erb
<h1>Editing order_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

app/views/order_products/index.html.erb
<%= button_to 'Continue to Shop', root_path, :method => 'get', :class => 'btn btn-info' %>
<h1 class="lead"><%= current_user.username %>'s Shopping Cart</h1>

<div class="table-responsive text-center">
  <table class="table table-hover lead">
    <thead>
      <tr>
        <th class="text-center">Quantity</th>
        <th class="text-center">Product</th>
        <th class="text-center">Price (AUD)</th>
        <th class="text-center">Subtotal (AUD)</th>
        <th class="text-center"></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td><b>Total</b></td>
        <td></td>
        <td></td>
        <td><b class="wobble-vertical totalPrice">$<%= @total %>0 AUD</b></td>
        <td>
          <% if @order_products.any? %>
            <%= button_to 'Checkout', checkout_path, :method => 'get', :class => 'btn btn-success', data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= button_to 'Back to shop', root_path, :method => 'get', :class => 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
    </tfoot>
    <tbody>
      <% @order_products.each do |order_product| %>
        <tr data-productID="<%= order_product.id %>">
          <td><%= order_product.quantity %></td>
          <td><%= order_product.product.title %></td>
          <td><%= number_to_currency order_product.product.price %> AUD</td>
          <td><%= number_to_currency order_product.product.price * order_product.quantity %> AUD</td>
          <td><%= button_to 'Remove', order_product, method: :delete, :class => 'btn btn-danger removeFromCart' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<small>* checkout will bring you to the payment page.</small>

app/views/order_products/new.html.erb
<h1>New order_product</h1>

<%= render 'form' %>

<%= link_to 'Back', order_products_path %>

app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>