config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :orders

  resources :products

  resources :charges

  resources :order_products

  get 'checkout' => 'order_products#checkout'
  

  root 'products#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplac</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="http://css-spinners.com/css/spinners.css" type="text/css">
  <%= javascript_include_tag 'application' %>
  <%= stripe_javascript_tag %>
  <%= csrf_meta_tags %>
</head>

<span id="header"></span>

<header>
  <!-- Bootstrap nav bar start here -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand colorize" href="/">Market<i class="italicise">Plac</i></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Keyword">
          </div>
          <button type="submit" class="btn btn-info">Search</button>
        </form>
        <ul class="nav navbar-nav">
          <li><a href="#" data-toggle="modal" data-target=".bs-about-modal-lg">About</a></li>
          <li><a href="#" data-toggle="modal" data-target=".bs-contact-modal-lg">Contact</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/" class="flash_msg disabled notice alert"><%= notice %><%= alert %></a></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.username, root_path, :class => 'disabled colorize' %></li>
            <li><%= link_to 'Setting', edit_user_registration_path %></li>
            <li><%= link_to 'Cart', order_products_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete', data: { confirm: 'Are you sure?' } %></li>

            <% if current_user.admin? %>
              <li><%= link_to "Add Product", new_product_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!-- Bootstrap nav bar ending -->
</header>

<body>
  <div class="site_container">

    <!-- Yield Container -->
    <div class="yield_container">
      <%= yield %>
    </div>
    <!-- End of Yield Container -->

  </div> <!-- End of site_container div -->

<!-- For the About's modal -->
<div class="modal fade bs-about-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content about-container">
      <h2 class="text-center lead"><b>About</b></h2>
      <!-- <img class="about-img" src="/images/WDI4.jpg" alt=""> -->
      <p class="lead about-content">Market<i class="italicise">Plac</i> is a ecommerce site that literally look good!</p>
    </div>
  </div>
</div> <!-- End the About's modal -->


<!-- For the Contact's modal -->
<div class="modal fade bs-contact-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content about-container">
      <h2 class="text-center lead"><b>Contact</b></h2>
      <!-- <img class="about-img" src="/images/WDI4.jpg" alt=""> -->
      <p class="lead contact-content">Contact me</p>
    </div>
  </div>
</div> <!-- End the Contact's modal -->

<p class="scrollToTop" style="display: inline;"><span>Jump to top</span></p>
</body>

</html>